### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (57,2) (19494,2) in ProximityReward

### ISSUE THREAD

**Issue by lnilya** [DBrughmans/NICE#6]
Hi there,

Thanks for providing this library.
I am a computational ecologist doing my PhD on plant-climate-interactions
We are very interested in using NICE especially due to the runtime. (DICE currently would take us weeks-months to run at full scale on an HPC, it is not really feasible).

However I can't get NICE to run. The error is always the same (for all 3 optimizations: proximity, sparsity, plausibility):

```
File ".../venv/lib/python3.11/site-packages/nice/__init__.py", line 50, in explain
    CF = self.optimizer.optimize(NN)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
 File ".../venv/lib/python3.11/site-packages/nice/utils/optimization/heuristic.py", line 23, in optimize
    CF_candidate = self.reward_function.calculate_reward(X_prune,CF_candidate)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File ".../venv/lib/python3.11/site-packages/nice/utils/optimization/reward.py", line 22, in calculate_reward
    score_prune = -self.data.predict_fn(previous_CF_candidate) + self.data.predict_fn(X_prune)
    
    ValueError: operands could not be broadcast together with shapes (57,2) (19494,2) 
```

### Reproduce error 

To reproduce the error I attached a pickle with my data (unzip it first):
[nice.pickle.zip](https://github.com/DBrughmans/NICE/files/13969526/nice.pickle.zip)

This is the code to run it:

```python
import pickle
from nice import NICE

if __name__ == '__main__':
    data = pickle.load(open("nice.pickle","rb"))


    #Add the predict function manually as it can't be pickled
    data["init_params"]["predict_fn"] = lambda x: data["svm"].predict_proba(x)

    niceCF = NICE(**data["init_params"])
    niceCF.explain(**data["explain_params"])
```

### A bit about my data:

- Data is 6 dimensional climate data and each input is a pixel on the map. I have already flattened it to 1D.
- Prediction is done via an sklearn support vector machine (with probability added)
- The two classes are 0 and 1 They define whether a plant will be stressed (and decrease in abundance) in the given climate or not. 
- I am trying to explain "why a plant decreases" by looking for CF explanations for every pixel where the plant is predicted to decrease

- The points where I need to generate CF examples might be very far off from the training data (since I use the model to predict across a wide range of locations, but the plant only occurs in a small subset). If there is some sort of "maximal distance" defined in the algorithm, maybe this leads to problems? 

### Thank you

I am really grateful if you find the time to look at this. I know how hard it is to maintain these libraries!

**Comment by DBrughmans** [comment]
Hi Inilya,

The .explain() method currently only supports explaining one instance each time it's called at the moment. In order to make your code work, you will have to loop over all instances that you want to explain.

The following code should work:

```
import pickle
from nice import NICE

if __name__ == '__main__':
    data = pickle.load(open("nice.pickle","rb"))


    #Add the predict function manually as it can't be pickled
    data["init_params"]["predict_fn"] = lambda x: data["svm"].predict_proba(x)

    niceCF = NICE(**data["init_params"])
    exp = []
    for i in range(data['explain_params']['X'].shape[0]):
        exp.append(niceCF.explain(
            data['explain_params']['X'][i:i+1, :],
            target_class= data['explain_params']['target_class'])
        )
```

Best regards,
Dieter

**Comment by lnilya** [comment]
Thanks that worked! I hope I will get the time to add some documentation and send it to you as a pull request.
